// packages/react/src/components/QueryTableRow.jsx
export default function QueryTableRow({name, query}){
    const loadingColor = query.isError ? "red" : query.isLoading? "yellow" : "green"
    const errorColor = query.isError && ! query.isLoading ? "red" : query.isLoading ? "yellow" : "green"
    return (
        <tr>
            <td>{name}</td>
            <td style={{color: loadingColor}}>{query.isLoading ? "true": "false"}</td>
            <td style={{color: errorColor}}>{query.isError ? "true": "false"}</td>
        </tr>
    )
}

// packages/svelte/src/routes/QueryTableRow.svelte
<script>
    export let name;
    export let query;

    let loadingColor = "inherit"
    let errorColor = "inherit"

    $: {
        loadingColor = query.isError ? "red" : query.isLoading? "yellow" : "green"
        errorColor = query.isError && ! query.isLoading ? "red" : query.isLoading ? "yellow" : "green"
    }
</script>
<tr>
    <td>{name}</td>
    <td style="color: {loadingColor}">{query.isLoading}</td>
    <td style="color: {errorColor}">{query.isError}</td>
</tr>
